ALTER TABLE project
    ADD COLUMN description TEXT;

ALTER TABLE project
    ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE project
    ADD COLUMN startedAt LONG NOT NULL DEFAULT CURRENT_TIMESTAMP;