ALTER TABLE project
    ADD COLUMN description TEXT;

ALTER TABLE project
    ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE project
    ADD COLUMN start_date DATE NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE project
    ADD COLUMN end_date DATE;