name: prcheck
on:
  pull_request:
    paths-ignore: 
    - 'workflow/**'
jobs:
  prcheck:
    name: tag
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven  
    
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
         
    - name: Build Backend
      if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
      run: |
        cd backend
        mvn -B package --file pom.xml    
        
    - name: Build Frontend
      if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
      run: |
       cd frontend
       npm ci
       npm run build --if-present
